---
Name: modeladminplusconfig
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - tractorcow/silverstripe-autocomplete:css/AutocompleteField.css
    - dft/silverstripe-modeladminplus:client/dist/css/admin.css
  extra_requirements_javascript:
    - tractorcow/silverstripe-autocomplete:javascript/AutocompleteField.js
    - dft/silverstripe-modeladminplus:client/dist/js/admin.js

SilverStripe\ORM\DataObject:
  extensions:
    - DFT\SilverStripe\ModelAdminPlus\DataObjectExtension
