---
Name: modeladminplusconfig
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - tractorcow/silverstripe-autocomplete:css/AutocompleteField.css
  extra_requirements_javascript:
    - tractorcow/silverstripe-autocomplete:javascript/AutocompleteField.js
    - i-lateral/silverstripe-modeladminplus:client/dist/js/admin.js

SilverStripe\ORM\DataObject:
  extensions:
    - ilateral\SilverStripe\ModelAdminPlus\DataObjectExtension

